name: couples_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  drift: ^2.23.1
  drift_flutter: ^0.2.4
  sqlite3_flutter_libs: ^0.5.30
  equatable: ^2.0.7
  just_audio: ^0.10.5
  image_picker: ^1.1.2
  record: ^6.1.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.4.2
  geolocator: ^13.0.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.1.3
  timezone: ^0.10.1
  json_annotation: ^4.9.0
  fl_chart: ^0.70.2
  web: ^1.1.1
  cupertino_icons: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.23.1
  build_runner: ^2.4.14

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/fonts/genres/zh/
    - assets/fonts/genres/en/

  fonts:
    - family: GenrePopZh
      fonts:
        - asset: assets/fonts/genres/zh/GenrePopZh.ttf
    - family: GenrePopEn
      fonts:
        - asset: assets/fonts/genres/en/GenrePopEn.ttf
    - family: GenreRockZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreRockZh.ttf
    - family: GenreRockEn
      fonts:
        - asset: assets/fonts/genres/en/GenreRockEn.ttf
    - family: GenreMetalZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreMetalZh.ttf
    - family: GenreMetalEn
      fonts:
        - asset: assets/fonts/genres/en/GenreMetalEn.ttf
    - family: GenreFolkZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreFolkZh.ttf
    - family: GenreFolkEn
      fonts:
        - asset: assets/fonts/genres/en/GenreFolkEn.ttf
    - family: GenreElectronicZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreElectronicZh.ttf
    - family: GenreElectronicEn
      fonts:
        - asset: assets/fonts/genres/en/GenreElectronicEn.ttf
    - family: GenreHipHopZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreHipHopZh.ttf
    - family: GenreHipHopEn
      fonts:
        - asset: assets/fonts/genres/en/GenreHipHopEn.ttf
    - family: GenreRnBZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreRnBZh.ttf
    - family: GenreRnBEn
      fonts:
        - asset: assets/fonts/genres/en/GenreRnBEn.ttf
    - family: GenreJazzZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreJazzZh.ttf
    - family: GenreJazzEn
      fonts:
        - asset: assets/fonts/genres/en/GenreJazzEn.ttf
    - family: GenreBluesZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreBluesZh.ttf
    - family: GenreBluesEn
      fonts:
        - asset: assets/fonts/genres/en/GenreBluesEn.ttf
    - family: GenreClassicalZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreClassicalZh.ttf
    - family: GenreClassicalEn
      fonts:
        - asset: assets/fonts/genres/en/GenreClassicalEn.ttf
    - family: GenreGuofengZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreGuofengZh.ttf
    - family: GenreGuofengEn
      fonts:
        - asset: assets/fonts/genres/en/GenreGuofengEn.ttf
    - family: GenreLightMusicZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreLightMusicZh.ttf
    - family: GenreLightMusicEn
      fonts:
        - asset: assets/fonts/genres/en/GenreLightMusicEn.ttf
    - family: GenreAmbientZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreAmbientZh.ttf
    - family: GenreAmbientEn
      fonts:
        - asset: assets/fonts/genres/en/GenreAmbientEn.ttf
    - family: GenreOSTZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreOSTZh.ttf
    - family: GenreOSTEn
      fonts:
        - asset: assets/fonts/genres/en/GenreOSTEn.ttf
    - family: GenreClubZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreClubZh.ttf
    - family: GenreClubEn
      fonts:
        - asset: assets/fonts/genres/en/GenreClubEn.ttf
    - family: GenreFunkZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreFunkZh.ttf
    - family: GenreFunkEn
      fonts:
        - asset: assets/fonts/genres/en/GenreFunkEn.ttf
    - family: GenreLatinZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreLatinZh.ttf
    - family: GenreLatinEn
      fonts:
        - asset: assets/fonts/genres/en/GenreLatinEn.ttf
    - family: GenreReggaeZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreReggaeZh.ttf
    - family: GenreReggaeEn
      fonts:
        - asset: assets/fonts/genres/en/GenreReggaeEn.ttf
    - family: GenreCountryZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreCountryZh.ttf
    - family: GenreCountryEn
      fonts:
        - asset: assets/fonts/genres/en/GenreCountryEn.ttf
    - family: GenrePunkZh
      fonts:
        - asset: assets/fonts/genres/zh/GenrePunkZh.ttf
    - family: GenrePunkEn
      fonts:
        - asset: assets/fonts/genres/en/GenrePunkEn.ttf
    - family: GenreIndieZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreIndieZh.ttf
    - family: GenreIndieEn
      fonts:
        - asset: assets/fonts/genres/en/GenreIndieEn.ttf
    - family: GenreExperimentalZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreExperimentalZh.ttf
    - family: GenreExperimentalEn
      fonts:
        - asset: assets/fonts/genres/en/GenreExperimentalEn.ttf
    - family: GenreLofiZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreLofiZh.ttf
    - family: GenreLofiEn
      fonts:
        - asset: assets/fonts/genres/en/GenreLofiEn.ttf
    - family: GenreACGZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreACGZh.ttf
    - family: GenreACGEn
      fonts:
        - asset: assets/fonts/genres/en/GenreACGEn.ttf
    - family: GenreOperaZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreOperaZh.ttf
    - family: GenreOperaEn
      fonts:
        - asset: assets/fonts/genres/en/GenreOperaEn.ttf
    - family: GenreNewAgeZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreNewAgeZh.ttf
    - family: GenreNewAgeEn
      fonts:
        - asset: assets/fonts/genres/en/GenreNewAgeEn.ttf
    - family: GenreGospelZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreGospelZh.ttf
    - family: GenreGospelEn
      fonts:
        - asset: assets/fonts/genres/en/GenreGospelEn.ttf
    - family: GenreIndustrialZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreIndustrialZh.ttf
    - family: GenreIndustrialEn
      fonts:
        - asset: assets/fonts/genres/en/GenreIndustrialEn.ttf
    - family: GenreEmoZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreEmoZh.ttf
    - family: GenreEmoEn
      fonts:
        - asset: assets/fonts/genres/en/GenreEmoEn.ttf
    - family: GenreVocalZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreVocalZh.ttf
    - family: GenreVocalEn
      fonts:
        - asset: assets/fonts/genres/en/GenreVocalEn.ttf
    - family: GenreChildrenZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreChildrenZh.ttf
    - family: GenreChildrenEn
      fonts:
        - asset: assets/fonts/genres/en/GenreChildrenEn.ttf
    - family: GenreInstrumentalRockZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreInstrumentalRockZh.ttf
    - family: GenreInstrumentalRockEn
      fonts:
        - asset: assets/fonts/genres/en/GenreInstrumentalRockEn.ttf
    - family: GenreMathProgZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreMathProgZh.ttf
    - family: GenreMathProgEn
      fonts:
        - asset: assets/fonts/genres/en/GenreMathProgEn.ttf
    - family: GenreKawaiiFutureZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreKawaiiFutureZh.ttf
    - family: GenreKawaiiFutureEn
      fonts:
        - asset: assets/fonts/genres/en/GenreKawaiiFutureEn.ttf
    - family: GenreHyperpopZh
      fonts:
        - asset: assets/fonts/genres/zh/GenreHyperpopZh.ttf
    - family: GenreHyperpopEn
      fonts:
        - asset: assets/fonts/genres/en/GenreHyperpopEn.ttf
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/genres/zh/NotoSansSC.ttf
    - family: NotoSerifSC
      fonts:
        - asset: assets/fonts/genres/zh/NotoSerifSC.ttf
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/genres/en/SpaceGrotesk.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
